"""Update PhotoExhibit model

Revision ID: 04146f51418c
Revises: 
Create Date: 2025-05-07 18:50:58.948076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04146f51418c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos_exhibit', sa.Column('photo_path', sa.String(length=255), nullable=False))
    op.drop_column('photos_exhibit', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos_exhibit', sa.Column('photo', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('photos_exhibit', 'photo_path')
    # ### end Alembic commands ###
