"""Add photo models and relationships

Revision ID: 92180aa8c341
Revises: 04146f51418c
Create Date: 2025-05-09 17:40:22.908371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92180aa8c341'
down_revision: Union[str, None] = '04146f51418c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos_culture')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos_culture',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('photo_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id_culture', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_culture'], ['culture.id'], name='photos_culture_id_culture_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='photos_culture_pkey')
    )
    # ### end Alembic commands ###
